server:
  port: 8080

# Basic Auth credentials the Scoring Engine will use to call US
lms:
  security:
    username: scoring_user
    # Use a strong password, consider externalizing this in real apps
    password: scoring_pwd_123!

# Configuration for calling the Scoring Engine
scoring:
  api:
    base-url: https://scoringtest.credable.io/api/v1
    # IMPORTANT: Obtain this token by calling the createClient API manually
    # after deploying YOUR service, providing YOUR endpoint URL and the credentials above.
    # Store securely (e.g., env var, Vault) in real apps.
    client-token: YOUR_GENERATED_UNIQUE_UUID_FROM_CREATE_CLIENT_API
    # Set to true to enable mocking, false to disable
    #    -> This is because the provided API from the base-url above throws a 404
    mock-enabled: true

# Configuration for calling CBS (Mocked)
cbs:
  api:
    username: admin
    password: pwd123
  kyc:
    wsdl-url: https://kycapitest.credable.io/service/customerWsdl.wsdl
  transaction:
    wsdl-url: https://trxapitest.credable.io/service/transactionWsdl.wsdl

# Retry configuration
retry:
  score-query:
    max-attempts: 5
    delay-ms: 5000 # 5 seconds

# Async thread pool (Spring Boot defaults are often sufficient)
spring:
  application:
    name: credable-lms
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
      thread-name-prefix: async-exec-

# Logging (Example - customize as needed)
logging:
  level:
    root: INFO
    io.credable.lms: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.retry: INFO